### ISSUE TITLE
关于速度变慢问题

### ISSUE THREAD

**Issue by time-river** [LiuXingMing/SinaSpider#2]
你好。
我使用SinaSpider1，连续运行24小时后速度会降为原来的1/2，这是为什么呢？

**Comment by LiuXingMing** [comment]
个人觉得是因为待爬队列和已爬队列太多，造成增删查改的速度变慢，因为重新启动后速度又变回来了。但是待爬队列和已爬队列都是放在内存里面的，所以重启程序的话会下载重复的信息，并没有“断点续爬”的功能，爬虫程序还不够完善。

**Comment by time-river** [comment]
假如是内存不够的话，第一次设置 DELAY=2 ， 24h 后速度变为原来 1/2 ；第二次设置 DELAY=1 ， 24h 后速度变为原来 1/2 。第三次运行中又开了一个 uwsgi 容器，速度也是 24h 后变为原来的 1/2 。这也太准时了吧！

假如是 cookies 的原因，设置 24h 后重新登录，速度还是会在 24h 后变为原来的 1/2 。

这是我昨天的一些设想。降速间隔太确定了。我看看连续运行48h的结果。
再次运行时候记录下日志。

thanks


Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=5.1&source=email_footer_2] On Sat, Apr 09, 2016 at 1:39 PM, 幸明老匹夫 < notifications@github.com [notifications@github.com] > wrote:
个人觉得是因为待爬队列和已爬队列太多，造成增删查改的速度变慢，因为重新启动后速度又变回来了。但是待爬队列和已爬队列都是放在内存里面的，所以重启程序的话会下载重复的信息，并没有“断点续爬”的功能，爬虫程序还不够完善。

**Comment by time-river** [comment]
这两天又观察了下记录：
没有再次出现变慢的迹象，若干小时后速度会回升。
因未重启容器，所以提供不了更详细的信息。
