### ISSUE TITLE
中文验证码问题

### ISSUE THREAD

**Issue by hechengyuan** [LiuXingMing/SinaSpider#52]
我把SinaSpider3的验证码识别那一块接入到SinaSpider1 中，经常会出现中文验证码，在敲入中文验证码后会验证失败。求解。

**Comment by hechengyuan** [comment]
我是通过换IP，或者用网页登录一下解决的。

**Comment by LiuXingMing** [comment]
在cookies.py或者spiders.py加上以下三行，设置编码格式。
import sys
reload(sys)
sys.setdefaultencoding('utf8')
